### ISSUE TITLE
TRV 14_Issues in payloads - Purchase Journey (Culture Heritage) - Single / multiple  QTY

### ISSUE THREAD

**Issue by Priyankapndy** [ONDC-Official/pramaan#1017]
Search -1------------------
1. In the payloads, the city code is hardcoded. Even if 055 is provided as input, it is being replaced with "*" without consuming the input from the initial form.
2. STATIC_TERMS should not be hardcoded from swagger 
3. SETTLEMENT_BASIS should not be an url it should be an string such as INVOICE_RECEIPT

on_search- 1---------------------

1, COURT_JURISDICTION should be city code such as std:011 not name of city 
2. The catalog currently contains hardcoded data, which needs to be updated so that NP-specific hardcoding from Swagger can be validated

on_search- 2& 3---------------------
ADDITIONAL_DETAILS_REQUIRED is not sent  in item.tags 
location_ids is not sent  in add_ons object
The catalog currently contains hardcoded data, which needs to be updated so that NP-specific hardcoding from Swagger can be validated

Select 1&2------------------
add_on was not selected for a particular item but the select has hardcoded add_on selected 

on_select 1----------------------------
order.items.fulfillment_ids:F2 is sent additioanlly 
ADDITIONAL_DETAILS_REQUIRED is marked as FALSE, where as initially it was marked as TrUE and basis of this only the form submission happens 
quantity.available was sent instead of quantity.selected in add_ons 

init----------------------------------------
As this multiple users flow but items only has one item object and that doesnt have parent_item_id 

on_init-------------------------------------
same issues till on_select
SETTLEMENT_AMOUNT is not calculated and was being hardcoded from swagger examples and other tags such as SETTLEMENT_BANK_CODE, SETTLEMENT_BANK_ACCOUNT_NUMBER are also hardcoded

confirm----------------------
payments.params.amount is incorrect as it is hardcoded to 800

on_confirm----------------------
same issues till on_select and on_init
authorization object is hardcoded 
payments.params.amount is incorrect as it is hardcoded to 800

on_status-----------------------------
For every status call, the on_status response is being returned with order.state = COMPLETE, which should not be the case. A CTA to mark the transaction as complete should instead be enabled on the UI.

Additionally:

Even when order.state is marked as COMPLETE, fulfillment.state is also being marked as COMPLETED.

fulfillment.authorization.status should be marked as CLAIMED.

created_at and updated_at values are being sent incorrectly

[Flow_2A.json](https://github.com/user-attachments/files/22018969/Flow_2A.json)
[Fow 1A (1).json](https://github.com/user-attachments/files/22018968/Fow.1A.1.json)

**Comment by shanusingh13** [comment]
Hi @Priyankapndy, team is working on it, will update once it is fixed

**Comment by DisasterDeveloper** [comment]
@Priyankapndy , issues has been fixed please check

**Comment by Priyankapndy** [comment]
We are unable to process due to blocker issue https://github.com/ONDC-Official/pramaan/issues/1063

**Comment by shanusingh13** [comment]
Hi @Priyankapndy  , issues has been fixed please check

**Comment by Priyankapndy** [comment]
Search -1------------------

In the payloads, the city code is hardcoded. Even if 055 is provided as input, it is being replaced with "*" without consuming the input from the initial form.- **Fixed** 
STATIC_TERMS should not be hardcoded from swagger - **Fixed** 
SETTLEMENT_BASIS should not be an url it should be an string such as INVOICE_RECEIPT - **Not Fixed** - Only fixed in on_select and remaining on_response it is wrong (trail is not maintained) 

on_search- 1---------------------

1, COURT_JURISDICTION should be city code such as std:011 not name of city **Fixed** 
2. The catalog currently contains hardcoded data, which needs to be updated so that NP-specific hardcoding from Swagger can be validated  **Fixed** 

on_search- 2& 3---------------------
ADDITIONAL_DETAILS_REQUIRED is not sent in item.tags **Fixed** 
location_ids is not sent in add_ons object **Fixed** 
The catalog currently contains hardcoded data, which needs to be updated so that NP-specific hardcoding from Swagger can be validated **Fixed** 

Select 1&2------------------
add_on was not selected for a particular item but the select has hardcoded add_on selected **Fixed** 

on_select 1----------------------------
order.items.fulfillment_ids:F2 is sent additioanlly **Fixed** 
ADDITIONAL_DETAILS_REQUIRED is marked as FALSE, where as initially it was marked as TrUE and basis of this only the form submission happens **Fixed** 
quantity.available was sent instead of quantity.selected in add_ons **Fixed** 

init----------------------------------------
As this multiple users flow but items only has one item object and that doesnt have parent_item_id **Not Fixed** as parent item is not conumed and trail is broken 

on_init-------------------------------------
same issues till on_select
SETTLEMENT_AMOUNT is not calculated and was being hardcoded from swagger examples **Fixed**
 and other tags such as
SETTLEMENT_BANK_CODE, SETTLEMENT_BANK_ACCOUNT_NUMBER are also hardcoded **Fixed**

confirm----------------------
payments.params.amount is incorrect as it is hardcoded to 800 **FIxed** 

on_confirm----------------------
same issues till on_select and on_init **Not FIxed** 
authorization object is hardcoded **Not FIxed** 
payments.params.amount is incorrect as it is hardcoded to 800 **FIxed** 

on_status-----------------------------
For every status call, the on_status response is being returned with order.state = COMPLETE, which should not be the case. A CTA to mark the transaction as complete should instead be enabled on the UI. **FIxed** 

Additionally:

Even when order.state is marked as COMPLETE, fulfillment.state is also being marked as COMPLETED. **Not FIxed**  

fulfillment.authorization.status should be marked as CLAIMED. **FIxed** 

created_at and updated_at values are being sent incorrectly  **Not FIxed**

**Comment by Priyankapndy** [comment]
@DisasterDeveloper Above issues are still pending please check

**Comment by DisasterDeveloper** [comment]
@Priyankapndy , these issues have been fixed , please check

**Comment by Priyankapndy** [comment]
Search -1------------------

In the payloads, the city code is hardcoded. Even if 055 is provided as input, it is being replaced with "*" without consuming the input from the initial form.- Fixed
STATIC_TERMS should not be hardcoded from swagger - Fixed
SETTLEMENT_BASIS should not be an url it should be an string such as INVOICE_RECEIPT - Not Fixed - Only fixed in on_select and remaining on_response it is wrong (trail is not maintained)  Fixed
on_search- 1---------------------

1, COURT_JURISDICTION should be city code such as std:011 not name of city Fixed
2. The catalog currently contains hardcoded data, which needs to be updated so that NP-specific hardcoding from Swagger can be validated Fixed

on_search- 2& 3---------------------
ADDITIONAL_DETAILS_REQUIRED is not sent in item.tags Fixed
location_ids is not sent in add_ons object Fixed
The catalog currently contains hardcoded data, which needs to be updated so that NP-specific hardcoding from Swagger can be validated Fixed

Select 1&2------------------
add_on was not selected for a particular item but the select has hardcoded add_on selected Fixed

on_select 1----------------------------
order.items.fulfillment_ids:F2 is sent additioanlly Fixed
ADDITIONAL_DETAILS_REQUIRED is marked as FALSE, where as initially it was marked as TrUE and basis of this only the form submission happens Fixed
quantity.available was sent instead of quantity.selected in add_ons Fixed

init----------------------------------------
As this multiple users flow but items only has one item object and that doesnt have parent_item_id Not Fixed as parent item is not conumed and trail is broken **Fixed** 

on_init-------------------------------------
same issues till on_select
SETTLEMENT_AMOUNT is not calculated and was being hardcoded from swagger examples Fixed
and other tags such as
SETTLEMENT_BANK_CODE, SETTLEMENT_BANK_ACCOUNT_NUMBER are also hardcoded Fixed

confirm----------------------
payments.params.amount is incorrect as it is hardcoded to 800 FIxed

on_confirm----------------------
same issues till on_select and on_init Not FIxed
authorization object is hardcoded ** Fixed**
payments.params.amount is incorrect as it is hardcoded to 800 FIxed

on_status-----------------------------
For every status call, the on_status response is being returned with order.state = COMPLETE, which should not be the case. A CTA to mark the transaction as complete should instead be enabled on the UI. FIxed

Additionally:

Even when order.state is marked as COMPLETE, fulfillment.state is also being marked as COMPLETED. **FIxed**

fulfillment.authorization.status should be marked as CLAIMED. FIxed

created_at and updated_at values are being sent incorrectly Not FIxed
