### ISSUE TITLE
FIS | PL | False positive Failures in report | Seller - Soft Trust

### ISSUE THREAD

**Issue by y0geshb** [ONDC-Official/pramaan#1074]
In pramaan the report is failing false positively even when the payload is intact 

[logs(5).json](https://github.com/user-attachments/files/22300267/logs.5.json)
[1757593912918_report.html](https://github.com/user-attachments/files/22300268/1757593912918_report.html)

@AmanSequelString this issue was not there earlier can you check and revert with fix

cc: @simranOndc

**Comment by Shreshthsharma0109** [comment]
Hi @y0geshb ,

Are all the failing test cases false positives? Could you please clarify which specific tests you are referring to?

**Comment by y0geshb** [comment]
@Shreshthsharma0109 the test cases that are related to xinput 

<img width="1162" height="399" alt="Image" src="https://github.com/user-attachments/assets/30bdbd95-d461-4bcf-bfd4-4ef07a1bb674" />

**Comment by Shreshthsharma0109** [comment]
@y0geshb Okay , Thank you. Checking these.

**Comment by Shreshthsharma0109** [comment]
@y0geshb , as per the docs, xinput.head.descriptor.name can be from ["Set Loan Amount", "Know your Customer"] but int he payload its 

<img width="653" height="236" alt="Image" src="https://github.com/user-attachments/assets/d04e0931-c8c3-4d25-934c-04e4da30dff1" />

<img width="1052" height="591" alt="Image" src="https://github.com/user-attachments/assets/e21f7577-c427-4483-ac6d-4794320086dc" />

**Comment by Shreshthsharma0109** [comment]
I have fixed this issue, you can check again and let me know if this persists.

**Comment by y0geshb** [comment]
<img width="1287" height="478" alt="Image" src="https://github.com/user-attachments/assets/32199fcb-bbd4-4128-9d3b-dccbfab00fcd" />

It is still not fixed

**Comment by AmanSequelString** [comment]
Hi @y0geshb I have just checked, this issue has been fixed, I have attached the report and screenshot for your reference

[61ec2a01-c67e-4383-87ea-ffb4e2a8d10a_report.zip](https://github.com/user-attachments/files/22378482/61ec2a01-c67e-4383-87ea-ffb4e2a8d10a_report.zip)

<img width="1762" height="665" alt="Image" src="https://github.com/user-attachments/assets/23581481-c394-4865-9f1f-e0ce61db6a3e" />

**Comment by y0geshb** [comment]
@AmanSequelString it is resolved now
