### ISSUE TITLE
1.2.5 Reports not getting generated for 1.2.5

### ISSUE THREAD

**Issue by pramaanONDC** [ONDC-Official/pramaan#1111]
**Organisation Name:** Ezstore

**Raised By:** [itsRajatKumar2](https://github.com/itsRajatKumar2)

**Test_id:** 1758609295069
**Id:** [ezstore.preprod.api.getondc.in](copy:ezstore.preprod.api.getondc.in)
**Version:** 1.2.5
**Environment:** Preprod
**Type:** RETAIL
**Domain:** ONDC:RET10

**Tests:**
- **Flow ID:** RET_1
  **Transaction ID:** [f7f2228c-ea25-4389-b71f-ac9d15684ca4](copy:f7f2228c-ea25-4389-b71f-ac9d15684ca4)
  **Type:** undefined
- **Flow ID:** IGM_4
  **Transaction ID:** [f7f2228c-ea25-4389-b71f-ac9d15684ca4](copy:f7f2228c-ea25-4389-b71f-ac9d15684ca4)
  **Type:** undefined

**Description:**
When we try to generate reports for IGM after running retail flow. its generating report for only Retail flow not For IGM,

All IGM logs are available in log file. 

IGM flow are not getting updated in any case. tried all IGM flows same error in all
Also same goes for RSF flow.

**Comment by pramaanONDC** [comment]
### 🙌 Thank You for Reaching Out!

We've received your ticket and our team will get back to you shortly.

---

### 🕒 Support Hours
**Monday to Friday:** 10:00 AM - 6:00 PM IST<br>**Weekend Support:** Available for *planned cases only*<br>

---

### 📍Response Time *(For issues raised via GitHub only)*
- 🟢 **Normal Issues:** Response within **4 business hours**
- 🔴 **Critical Issues:** Response within **2 business hours**

---

### Support Call Schedule:

| 🛠 **Domain** | 🕒 **Schedule** | 🔗 **Join / Calendar Link** |
|--------------|----------------|:---------------------------:|
| 🛍 Retail & Logistics | Daily, 4:00-5:00 PM IST | [Join](https://meet.google.com/ntx-jbjg-ykj) |
| 🛺 Mobility | Book a Slot | [Mobility Calendar](https://calendar.app.google/sKav2Du1mWofYbfG7) |
| 💸 Financial Services | Book a Slot | [Financial Services Calendar](https://calendar.app.google/8fvADhXshu53tvQ38) |

**Comment by AmanSequelString** [comment]
Hi @itsRajatKumar2, the version for IGM calls should be same as the version of parent calls,
like here the version for retail is 1.2.5 and you are testing igm for retail so, your version for igm calls should be 1.2.5

**Comment by AmanSequelString** [comment]
[file_20250926110350_8335.zip](https://github.com/user-attachments/files/22559063/file_20250926110350_8335.zip)

**Comment by AmanSequelString** [comment]
@pooja-1102  this is resolved, i guess we can close it!!

**Comment by itsRajatKumar2** [comment]
its not fixed yet @AmanSequelString

**Comment by AmanSequelString** [comment]
Hi @itsRajatKumar2  you are still sending version as 2.0.0 in IGM calls, that's why you are getting an error in generating report, I am attaching screenshot for your reference

<img width="803" height="501" alt="Image" src="https://github.com/user-attachments/assets/2df85c33-6bfb-4ebb-b926-66bd52bbf7fb" />

**Comment by AmanSequelString** [comment]
Hi @itsRajatKumar2 I am attaching IGM report for the updated transaction_id you have shared

[37e225d4-377a-4b20-9d05-8a09174f13f6_report.html](https://github.com/user-attachments/files/22600244/37e225d4-377a-4b20-9d05-8a09174f13f6_report.html)

**Comment by itsRajatKumar2** [comment]
@AmanSequelString  this is the test ID for IGM refund flow, RSF both flow recon and on_recon 1759228008761
will share test id for other IGM flow Soon.

**Comment by AmanSequelString** [comment]
[95cdc43a-72ec-42ce-bd4d-d89a3a7eabf2_report.html](https://github.com/user-attachments/files/22635011/95cdc43a-72ec-42ce-bd4d-d89a3a7eabf2_report.html)
the above attached report is for IGM (REFUND) flow

[Flow_1_report.html](https://github.com/user-attachments/files/22635025/Flow_1_report.html)

and this one is for 1A

**Comment by AmanSequelString** [comment]
[ezstore.html](https://github.com/user-attachments/files/22635554/ezstore.html)

**Comment by itsRajatKumar2** [comment]
@AmanSequelString  is it fixed ??

**Comment by AmanSequelString** [comment]
@itsRajatKumar2 ain't you able to generate report still?

**Comment by itsRajatKumar2** [comment]
HI @AmanSequelString 

 Can you please share reports for this test IDs and txn ids

BAP_ID: ezstore.preprod.api.getondc.in
RET10

IGM Flow Refund 6B
Txn id: dfdebbe4-b51a-4cb8-9018-a14ff0cc2fff
Test Id: 1760612514300

IGM Flow Replacement 6C
Txn id: 343d3955-5711-4029-8180-1520e31743f7
Test Id: 1760640418347

IGM Flow Cancel 6D
Txn id: e844cecd-92df-4dc7-bc6c-57cb0f245ba4
Test Id: 1760642423340

IGM Flow No Action 6E
Txn id: 9560b9aa-ed66-4772-903a-8306d568449d
Test Id: 1760676252483

RSF Flow 10A Recon
Txn id: 16715b34-94c8-46ea-862d-c05a2f81a6d0
Test Id: 1760640418347

RSF Flow 10B On_Recon
Txn id: 1a1a3cee-b935-4474-85c1-1e502f16f2a8
Test Id: 1760640418347

RSF Flow: 4A Full Return
Txn id: 8293c1dd-b339-427f-902f-4215ea2ace29
Test Id: 1760676743812

**Comment by anuraag-m-irutom** [comment]
@AmanSequelString We are still unable to generate reports for IGM and RSF. It has been more than a month, could you share any ETA on the fix? This is blocking our QA. It is not feasible to reach out to you folks generate the reports manually.

**Comment by pooja-1102** [comment]
@ayush-yadav1999 please fix this on priority.

**Comment by Nirdosh3312** [comment]
Hey @pooja-1102 @anuraag-m-irutom @itsRajatKumar2 This has been fixed and deployed. Can you please check now once  and do let me know if you have any concerns ?

**Comment by anuraag-m-irutom** [comment]
@Nirdosh3312 This seems to be resolved now. I was able to generate report for 6B IGM flow.

**Comment by anuraag-m-irutom** [comment]
@Nirdosh3312, @pooja-1102  Looks like the issue is still present in 10A and 10B. Unable to generate reports. Please check.

<img width="3454" height="1404" alt="Image" src="https://github.com/user-attachments/assets/6201478b-efd0-4276-b54d-1e202919e730" />

For 6D and 6E unable to download reports

<img width="3382" height="1334" alt="Image" src="https://github.com/user-attachments/assets/6c373e73-e4a5-4611-b9a9-0884291f84fb" />

**Comment by ayush-yadav1999** [comment]
Hi @anuraag-m-irutom, can you please try to generate the report again as this has been fixed and deployed. Do let me know after you check.

**Comment by anuraag-m-irutom** [comment]
@ayush-yadav1999 I'm was able to generate reports for 10A, 10B, 6D and 6E. Thanks for fixing this.

**Comment by ayush-yadav1999** [comment]
@anuraag-m-irutom, Thanks for the update. @pooja-1102 can we close this issue ?
