### ISSUE TITLE
TRV 14 | Entry Pass - FLow 3 User cancelleation

### ISSUE THREAD

**Issue by Priyankapndy** [ONDC-Official/pramaan#1140]
1- Incorrect quote calculation for cancelled quantities

If a single ticket costs ₹350 and the quantity is 2, then after cancellation the quote item price should be -700, but currently -350 is being shown.
a) Due to this, the quote.breakup price is calculated incorrectly.
b) As a result, the settlement amount is also computed incorrectly.

Cancellation reason ID inconsistency

2-The cancellation reason ID changes from 001 in soft cancel to 000 in confirm cancel.

Artifacts - 

[file_20251007085731_3393.json](https://github.com/user-attachments/files/22743549/file_20251007085731_3393.json)

**Comment by DisasterDeveloper** [comment]
@Priyankapndy, this has been done, will be deployed by EOD

**Comment by DisasterDeveloper** [comment]
@Priyankapndy , this has been fixed , please check

**Comment by Priyankapndy** [comment]
1- FIxed and retested 

2 Not fixed hence reopening this issue 

[4A User cancel.json](https://github.com/user-attachments/files/22950347/4A.User.cancel.json)
