### ISSUE TITLE
Sachet insurance | BAP terms not being sent in Payloads and false positive validations

### ISSUE THREAD

**Issue by y0geshb** [ONDC-Official/pramaan#1347]
1. BAP/BPP_Terms were not being sent in the payloads nor being consumed (implement different static terms to check trail)
2. Report failures 
on_search_I, II and III - catalog.tags.list.descriptor.name should be string - false positive
on_init, on_confirm, on_update message.catalog.tags - need clarity
on_init message.order.payments.url -false positive (was updated in contract)

 Report link :  https://pramaan.ondc.org/beta/preprod/testing/seller/download-report/8704aef9-8985-4b8a-9c45-2321187d3889/1764594862149

Transaction id : 78585634-1c22-417b-9be9-7350ab2273ee

Other validations were not captured in the report which added in this sheet 
https://docs.google.com/spreadsheets/d/14De9fHNPOlO-6flxFR2dMjMLUo4YlBm3fL5c6n3ESBM/edit?gid=0#gid=0

CC: @ravibhansali10

**Comment by y0geshb** [comment]
**https://pramaan.ondc.org/beta/preprod/testing/seller/download-report/8704aef9-8985-4b8a-9c45-2321187d3889/1764923237754**

also do check for items tags list failures in on_confirm and on_update

**Comment by Nirdosh3312** [comment]
Sure @y0geshb, I am on this and will update as soon as it is deployed.

**Comment by Nirdosh3312** [comment]
Hey @y0geshb, 
The following issues have been fixed and deployed on Pramaan.

> 
    BAP/BPP_Terms were not being sent in the payloads nor being consumed (implement 
    different static terms to check trail)
    Report failures
    on_search_I, II and III - catalog.tags.list.descriptor.name should be string - false positive
    on_init, on_confirm, on_update message.catalog.tags - need clarity
    on_init message.order.payments.url -false positive (was updated in contract)

For the following issue, I am working currently and will be deploying them in sometime 

> 
    Other validations were not captured in the report which added in this sheet


Please let me know if there is anything else that is needed.

**Comment by y0geshb** [comment]
Not able to retest as was struck at search_3 with an nack
e8b2d7b9-f977-46f3-8c8a-db866a2bdc5d

<img width="1060" height="900" alt="Image" src="https://github.com/user-attachments/assets/d284df56-df04-408b-8cc4-ee966f351b9f" />

**Comment by y0geshb** [comment]
@Nirdosh3312 reports still has issue, as the Buyer report is blank and seller report throwing failures, Payloads are still missing BPP_TERMS from mock seller end

[file_20251211075710_9990.html](https://github.com/user-attachments/files/24097473/file_20251211075710_9990.html)
[file_20251211075919_5942.html](https://github.com/user-attachments/files/24097472/file_20251211075919_5942.html)

**Comment by y0geshb** [comment]
@Nirdosh3312 BAP_Terms were not being sent in the payloads of search

Transaction id 3735160d-e1fc-4f31-82cb-ce3fdbb983f3
