### ISSUE TITLE
Logistics Buyer | Nearshop NP| report failures

### ISSUE THREAD

**Issue by pooja-1102** [ONDC-Official/pramaan#135]
Flow 1: Order to confirm to fulfilment
Transaction id: af19754c-3a90-450e-866e-e6194b0d9e4e

1). logistics seller mock: on_search is sending all the categories when search api asked for immediate delivery
2). mock seller on_confirm sending tracking as false but on_track showing active status with details
3). sending NACK when extra attribute (order.items[0].descriptor.name) is available in update api
4). Fulfillments.id is changing from on_confirm to update api but not failing on report

Flow 2 RTO Flow (Return Back to Seller/Liquidation)
transaction id: c2ae77b1-5835-4eb5-83db-0158627a5da0
on_cancel: sending state.descriptor.code-> cancelled, it should be RTO-initiated in on_cancel and on_status should send RTO-delivered/dispose.

**Comment by Nirdosh3312** [comment]
Hi @pooja-1102, I have updated the mentioned points in the following manner. 

> 1). logistics seller mock: on_search is sending all the categories when search api asked for immediate delivery

Since this is on_search API, We were publishing the entire catalog. @simranOndc Please let us know if we need to send only the category asked in the search intent or the entire catalog.

> 2). mock seller on_confirm sending tracking as false but on_track showing active status with details
       
 We are now sending tracking as true in the on_confirm API

> 3). sending NACK when extra attribute (order.items[0].descriptor.name) is available in update api
       
 The Validator Schema has been updated to support the additional property


> 4). Fulfillments.id is changing from on_confirm to update api but not failing on report
       
 The test cases will be added for this. @AmanSequelString Please do so

---


For the point mentioned here 

> Flow 2 RTO Flow (Return Back to Seller/Liquidation)
transaction id: c2ae77b1-5835-4eb5-83db-0158627a5da0
on_cancel: sending state.descriptor.code-> cancelled, it should be RTO-initiated in on_cancel and on_status should send RTO-delivered/dispose.

The NP is selecting the Return Item in the /init API. We have a logic that expects that the forward item is to be selected in the /init API and based on that we add the return item while initiating the RTO flow. Here, in fulfillments ideally there would be two objects one for the forward journey which should be in **_Cancelled_** state and one for RTO flow which has the state as **_RTO-Initiated_**, since the mentioned logic is not working due to item mismatch thus you are getting this behaviour.

**Comment by AmanSequelString** [comment]
@Nirdosh3312  okay sure

**Comment by AmanSequelString** [comment]
Hi @pooja-1102  this has been resolved, will be merged by the EOD!, please recheck the issue and let me know if it still exists

**Comment by pooja-1102** [comment]
@AmanSequelString I am getting this issue for current run as well for the same transaction id when generated https://pramaan.ondc.org/beta/preprod/gui/iframe/f43b5751-204e-445e-95a2-1e3650e6d9aa/logsandreport/

**Comment by pooja-1102** [comment]
@AmanSequelString plesae update on this

**Comment by pooja-1102** [comment]
Flow 1: Order to confirm to fulfilment
Transaction id: 8d4353b3-a39e-4007-97ae-28bc7dc3b015
preprod.effimove.in

1). logistics seller mock: on_search is sending all the categories when search api asked for immediate delivery- @simranOndc please confirm
2). mock seller on_confirm sending tracking as false but on_track showing active status with details-fixed
3). sending NACK when extra attribute (order.items[0].descriptor.name) is available in update api-fixed
4). Fulfillments.id is changing from on_confirm to update api but not failing on report-still faces this type of issues

**Comment by AmanSequelString** [comment]
@pooja-1102  working on it, first issue has been fixed, rest are in process

**Comment by simranOndc** [comment]
@AmanSequelString Please make sure this is done on priority, many logistics NPs are in pipeline.

**Comment by AmanSequelString** [comment]
Hi @pooja-1102  as i can see there's no update call in first flow, that's why in first flow there is no check for fullfillment_id, attaching the screenshot for your reference

![Image](https://github.com/user-attachments/assets/7ee1f16c-d9db-4d20-bf69-dd18e180a749)

**Comment by pooja-1102** [comment]
@AmanSequelString this is regarding flow 3 . now this test case is available on report

<img width="1792" height="873" alt="Image" src="https://github.com/user-attachments/assets/3c37d104-2b4b-4184-8392-afdf0fb6fb7d" />

**Comment by AmanSequelString** [comment]
Hi @pooja-1102  i have fixed this issue, will be deployed in next 10 minutes, please verify and let me know

**Comment by pooja-1102** [comment]
@AmanSequelString still facing same issue

Pramaan Test Report ID: 1760422937244

**Comment by pooja-1102** [comment]
@AmanSequelString now fixed

<img width="1792" height="944" alt="Image" src="https://github.com/user-attachments/assets/07f23a30-b482-449f-86d9-c0ee9db0fd86" />
