### ISSUE TITLE
FIS | Working Capital | Hardcoded unrealistic values for pre-part payment and hardcoded values for loan drawdown

### ISSUE THREAD

**Issue by y0geshb** [ONDC-Official/pramaan#225]
Pramaan is sending a hardcoded pre-part payment value of ₹10,00,000. If the NP’s loan amount is only ₹5,00,000, this would completely break the implementation, and since the NP is sometimes NACKing the request, we cannot proceed with the prepayment flow.

In credit drawdown, a hardcoded value of ₹4,00,000 is being sent. If the credit line assignment is for a lower amount, it will break the logic.

[SellerPrePartPaymentFlowLog27.json](https://github.com/user-attachments/files/19533389/SellerPrePartPaymentFlowLog27.json)

@simranOndc

**Comment by DisasterDeveloper** [comment]
@y0geshb , this has been fixed

**Comment by Aniketdhama** [comment]
@y0geshb  Kindly review this

**Comment by AmanSequelString** [comment]
@simranOndc Kindly note that this ticket has not received any response for the past two weeks. Please mark it as done, if no further action is pending.

**Comment by simranOndc** [comment]
@y0geshb please close this.

**Comment by y0geshb** [comment]
We had flagged this issue during the initial FINAGG QA phase and after NPs QA was cleared we requested NP to retest all flows. However, retesting is still pending from NPs end, so this issue was not reviewed.

Alternatively when checked from our mock-to-mock,  **"Update Base Transaction"** CTA was not working. Attaching video and logs for reference.
Without updating the base transaction, the flow cannot move to the pre-part payment stage, and hence, Pre pay amount couldn't be verified.

@simranOndc 


[Artifacts.zip](https://github.com/user-attachments/files/19943989/Artifacts.zip)

**Comment by AmanSequelString** [comment]
@Aniketdhama this issue still persists, please check this out!!

**Comment by Aniketdhama** [comment]
@AmanSequelString  The issue has been resolved.

**Comment by AmanSequelString** [comment]
Hii @y0geshb please recheck the issue and let me know iif it still exists!!

**Comment by y0geshb** [comment]
cant retest due to blocker issue https://github.com/ONDC-Official/pramaan/issues/1153
