### ISSUE TITLE
Issues Observed During IGM2.0 Testing on Praman

### ISSUE THREAD

**Issue by SomGSS** [ONDC-Official/pramaan#297]
Dear Praman Team,

I hope you're doing well.

While testing the IGM2.0 flow on Praman as a seller, I encountered a couple of issues that I'd like to bring to your attention:

Incomplete Action History in Issue Request:
After creating an issue, I sent a response with actions.description.code as PROCESSING (solicited), followed by an unsolicited on_issue with actions.description.code updated to INFO_REQUESTED. I received an ACK in response.
However, on the Praman site, when I clicked on the "Share Information" button, I received the issue request, but the action history was incomplete. It only displayed:

actions.description.code: PROCESSING

actions.description.code: INFO_REQUESTED
The following expected actions were missing from the history:

actions.description.code: OPEN

actions.description.code: PROCESSING

actions.description.code: INFO_REQUESTED

actions.description.code: INFO_PROVIDED

Missing Option for Resolution Selection:
While trying to provide a refund as a resolution, there was no option available on the Praman interface to select the resolution type. This is blocking the refund flow.

Kindly look into these issues and let me know if any further inputs are needed from my side.

Best regards,
Somanath Ojha

[12.json](https://github.com/user-attachments/files/19698976/12.json)

**Comment by Nirdosh3312** [comment]
Hi @SomGSS The issue has been resolved, This was occuring due to a typo over the swagger where INTERFACING_NP was typed as INFERENCING_NP. Please try now.

**Comment by SomGSS** [comment]
No it's not resolved yet. I'm not getting actions.description.code: INFO_PROVIDED in issue request after sending on_issue actions.description.code: INFO_REQUESTED

**Comment by Nirdosh3312** [comment]
@SomGSS Please share transaction_id.

**Comment by SomGSS** [comment]
96cd2144-d9c5-444e-aa7a-3e93514f5e38

**Comment by pooja-1102** [comment]
@SomGSS can you please confirm, is it resolved?
