### ISSUE TITLE
init payment issue

### ISSUE THREAD

**Issue by Sudhi-S-2003** [ONDC-Official/pramaan#463]
{
  "context": {
    "domain": "ONDC:RET11",
    "action": "on_init",
    "country": "IND",
    "city": "std:011",
    "core_version": "1.2.0",
    "bap_id": "ondc.eatiko.com",
    "bap_uri": "https://ondc.eatiko.com/api/v1/ONDC",
    "bpp_id": "pramaan.ondc.org/beta/preprod/mock/seller",
    "bpp_uri": "https://pramaan.ondc.org/beta/preprod/mock/seller",
    "transaction_id": "trn_c56fce37-5b70-4c2a-b8cc-dc4ac85f282a",
    "message_id": "c6820068-b25d-4696-bbde-4b9bac52892f",
    "timestamp": "2025-05-06T05:55:17.389Z"
  },
  "message": {
    "ack": {
      "status": "Nack"
    },
    "error": {
      "type": "DOMAIN-ERROR",
      "code": "20000",
      "message": "[\"\\\"message.order.payment.@ondc/org/settlement_details[0].upi_address\\\" is not allowed to be empty\"]"
    }
  }
}

**Comment by Sudhi-S-2003** [comment]
Pass upi_address as a non-empty string only when the payment type is 'UPI'. Do not pass upi_address at all for NEFT and RTGS—omit the field entirely. An empty string ("") is never valid for upi_address, regardless of payment type. If you're currently passing upi_address: "" for NEFT, that is incorrect and must be fixed by removing the field completely.

**Comment by Nirdosh3312** [comment]
Hey @Sudhi-S-2003 Sure, We'll be making the appropriate changes at our end. @pooja-1102 Are we aligned with the expected change here to be done on Pramaan. Please let me know, We'll make the changes accordingly.

**Comment by kartikaysharma1234** [comment]
Hi @Sudhi-S-2003 Can you check again and let me know if this still persists.

**Comment by Sudhi-S-2003** [comment]
Hi @kartikaysharma1234  ,

  yes still issue persists

[Eatiko_FLOW(05-07-2025).json](https://github.com/user-attachments/files/21071935/Eatiko_FLOW.05-07-2025.json)

**Comment by simranOndc** [comment]
@Nirdosh3312 is this closed??

**Comment by Nirdosh3312** [comment]
@simranOndc, The issue will be deployed and should be resolved. Apologies for the inconvenience

**Comment by pallaviwemotive** [comment]
@Sudhi-S-2003 Can you plz check and confirm on this

**Comment by Sudhi-S-2003** [comment]
[EATIKO_FLOW\[11-07-2025.20.48\].json](https://github.com/user-attachments/files/21185644/EATIKO_FLOW.11-07-2025.20.48.json)

@Nirdosh3312  @simranOndc  @pallaviwemotive  issue still exist .

**Comment by pooja-1102** [comment]
@kartikaysharma1234 please check

**Comment by kartikaysharma1234** [comment]
@pooja-1102 @Sudhi-S-2003 Can you please check again.

**Comment by kartikaysharma1234** [comment]
Hi @Sudhi-S-2003 Is it resolved?

**Comment by Sudhi-S-2003** [comment]
Fix has been verified. Closing the issue.
