### ISSUE TITLE
Tensor Solution Tech pvt ltd. | RET10, Buyer, 1.2.0 | Facing issue in return flow

### ISSUE THREAD

**Issue by pallaviwemotive** [ONDC-Official/pramaan#495]
In case of partial return and full return below issue present in pramaan seller

1. Return approved on_update call not sent
2. In return picked on_update :- Order contains 1 quantity of item and it is requested to return then ongoing item value at item section should be 0 but it remains same, quote.price fails to update, quote trail missing in fulfillment.tags 
3.  As quote not updated in return picked so buyer fails to send refund update call which we need to test.  please refer to details below  tranasaction ID - d583b6f6-3b43-455a-b929-e05dec931758 , BAP id - api.mobibharat.com

**Comment by AmanSequelString** [comment]
@Nirdosh3312 this is on priority, please make it fix

**Comment by pallaviwemotive** [comment]
[RETAIL_api.mobibharat.com (3).xlsx](https://github.com/user-attachments/files/20721464/RETAIL_api.mobibharat.com.3.xlsx)

**Comment by kartikaysharma1234** [comment]
@pallaviwemotive most of the issues has been fixed,
But i need clarity on this  Order contains 1 quantity of item and it is requested to return then ongoing item value at item section should be 0 but it remains same this line because as I see in swagger it I not changing the quantity


i am attaching pic for your reference

![Image](https://github.com/user-attachments/assets/60be2ce8-5c39-4bf8-afba-8670a4a86964)****

**Comment by pallaviwemotive** [comment]
Please check this transaction id dc2d52ba-f38f-491a-a139-aa56d690e85c issue still persist
