### ISSUE TITLE
IGM V2.0.0 | MPerito Seller NP | False cases are failing in on_issue status

### ISSUE THREAD

**Issue by Priyankapndy** [ONDC-Official/pramaan#632]
False cases are failing in report in on_issue_status 

![Image](https://github.com/user-attachments/assets/71e0e40f-803a-4d02-9a99-17cd3e143173)

Please refer attached logs 

[6B.json](https://github.com/user-attachments/files/20723163/6B.json)

**Comment by AmanSequelString** [comment]
@Priyankapndy This has been fixed, will be merged by the End of Day

**Comment by Priyankapndy** [comment]
@AmanSequelString Can you please attach report as issue was not fixed
