### ISSUE TITLE
FIS | Health Insurance | Optional Attributes need to be marked optional in Report

### ISSUE THREAD

**Issue by y0geshb** [ONDC-Official/pramaan#67]
Health Insurance Report should mark optional Test cases, as specified in the Swagger documentation.

Refer https://ondc-official.github.io/ONDC-FIS-Specifications/?branch=draft-FIS13-health&flowId=Health+Insurance+Application&tabId=%23attribute#attribute

Report id : 1739181582016 

![Image](https://github.com/user-attachments/assets/0db2e39a-49d5-4b1a-94da-210085734348)

NP : BAGIC

**Comment by Nirdosh3312** [comment]
@y0geshb / @simranOndc This is done. Please check.

**Comment by y0geshb** [comment]
Hi @Nirdosh3312 Test Report ID: 1741153302143 This is the latest report for BAGIC. Please review the report, as optional fields are inconsistently marked

**Comment by Nirdosh3312** [comment]
Hi @y0geshb The report was generated on 5th March, meanwhile the change was pushed on Saturday Evening.

**Comment by y0geshb** [comment]
@nirdosh Generated the following report today, yet discrepancies persist in the report, as seen in the shared snippet.

Report ID: 1741598987557

![Image](https://github.com/user-attachments/assets/1cad294e-6bfe-4969-a191-51427e63dfad)

CC: @simranOndc

**Comment by Nirdosh3312** [comment]
@simranOndc / @y0geshb PR for this has been merged and should resolve the issue.

**Comment by y0geshb** [comment]
@Nirdosh3312 @AmanSequelString  Please ensure that all optional attributes are correctly marked as optional in the report. As shown in the attached snippets, some attributes are still not marked appropriately. Additionally, there is one false positive case failing for message.order.quote.breakup[2] and decimal rounding issue

CC: @simranOndc 
Pramaan Test Report ID: 1742212153643

![Image](https://github.com/user-attachments/assets/1f54f971-a8f2-48a4-b33d-5945e7a121d6)

![Image](https://github.com/user-attachments/assets/7bffa592-6c45-4d06-8d0f-f0e0dc9a719f)

![Image](https://github.com/user-attachments/assets/65610712-3b75-43e0-a06f-d02eba4b0b7a)

**Comment by y0geshb** [comment]
Need this issue to be resolved as this is failing for all the HI sellers

![Image](https://github.com/user-attachments/assets/aeccd142-200b-46f9-901b-f18e931e5010)

![Image](https://github.com/user-attachments/assets/e4acf01d-3a86-4287-ae11-fb1ce011ee6b)

**Comment by simranOndc** [comment]
@AmanSequelString is this deployed? @Nirdosh3312

**Comment by AmanSequelString** [comment]
Hi @y0geshb this is fixed and deployed too, please check it again!

**Comment by y0geshb** [comment]
As there are no SNP in HI, this would be tracked, closing this for now
