### ISSUE TITLE
Logistics Buyer  | v1.2.5 | validations/testcases not available when buyer is sending authorization as OTP in search request.

### ISSUE THREAD

**Issue by pooja-1102** [ONDC-Official/pramaan#670]
All flows
Bap id: ondc.test.bms.qwipo.com
Log10

if /search api is sending authorisation as OTP update api should have validation that authorisation with dynamic OTP should be available.

**Comment by pooja-1102** [comment]
@AmanSequelString This is dependent on dynamic otp concept. if search request is showing authorisation as "OTP". then start.instructions will have code as "4" and short_desc should not be there, And Authorisation object with below details should be there
            
              "type":"OTP",
              "token":"OTP code",

Same will be applied in case of end.instruction(only instructions.code will 1). @abhinavv245  please confirm

**Comment by AmanSequelString** [comment]
Hi @pooja-1102 this has been resolved, will be on prod by the EOD

**Comment by pooja-1102** [comment]
@AmanSequelString this is still not fixed: 
incorrect payload :

[file_20250630100322_3925 (1).json](https://github.com/user-attachments/files/20990918/file_20250630100322_3925.1.json)


corrected:
"flow_name": "Flow 1D: Order to confirm to fulfillment - Immediate Delivery (Forward flow)",
"flow_id": "LOG10_4",
"transaction_id": "f12cd92a-a6d6-4610-b6e1-fe58c01d1f46",

**Comment by shanusingh13** [comment]
Hi @pooja-1102, this issue has been fixed, please check again and do let me know if it still exists

**Comment by pooja-1102** [comment]
@shanusingh13 tested with previous data, but don't see any new test case for authorization.
Test Report ID: 1753353616599

**Comment by shanusingh13** [comment]
Hi @pooja-1102, this issue has been fixed, please check again and do let me know if it still exists

**Comment by pooja-1102** [comment]
@shanusingh13 generated the report for earlier data(as no new V1.2.5 Np available ). but don't see any new test case under update api.

Pramaan Test Report ID: 1756722742191

**Comment by shanusingh13** [comment]
Hi @pooja-1102, this issue has been fixed, please check again and do let me know if it still exists

**Comment by pooja-1102** [comment]
@shanusingh13 can be tested with new NP on v1.2.5
