### ISSUE TITLE
Logistics Buyer | v1.2.5 | test cases are optional but showing mandatory on Pramaan

### ISSUE THREAD

**Issue by pooja-1102** [ONDC-Official/pramaan#759]
<img width="1770" alt="Image" src="https://github.com/user-attachments/assets/e1dc08a4-ab08-4634-852a-4d42eedae423" />
<img width="1770" alt="Image" src="https://github.com/user-attachments/assets/7c23bd87-c740-4da7-9f68-5a10dff2576b" />
<img width="1770" alt="Image" src="https://github.com/user-attachments/assets/cd938dc7-fa46-423f-adb9-00d1e34f5e59" />

Details:
test id:  1751281710752
Logistics Buyer

**Comment by shanusingh13** [comment]
Hi @pooja-1102, this issue has been fixed.

![Image](https://github.com/user-attachments/assets/9df02a51-5e8b-4635-80ba-2ee26b7b9bcf)

![Image](https://github.com/user-attachments/assets/c525a562-046b-4308-9f49-fc0fcf81c3f9)

![Image](https://github.com/user-attachments/assets/40176608-94ac-4f27-a3db-3fe1d52fc318)

**Comment by pooja-1102** [comment]
@AmanSequelString few of the caes are still failing.

<img width="1792" alt="Image" src="https://github.com/user-attachments/assets/04e39c3d-e162-4698-bbb2-1f02fe8b9ba9" />
<img width="1792" alt="Image" src="https://github.com/user-attachments/assets/75c1b40c-044e-4117-a008-90930739723f" />

**Comment by AmanSequelString** [comment]
Hi @pooja-1102 MinLength test cases are not marked as optional in the report by default. However, if the parent test case is marked as optional, then the corresponding MinLength test case is also treated as optional.

**Comment by pooja-1102** [comment]
@AmanSequelString how will NP get to know this thing, and Repport will never come as passed.

**Comment by Shreshthsharma0109** [comment]
Hi @pooja-1102 ,
I have fixed this and will be live by eod.
Attaching a screenshot for your reference.

<img width="1217" height="642" alt="Image" src="https://github.com/user-attachments/assets/96391225-0ca6-4d18-ba06-1326d8a7e96f" />
