### ISSUE TITLE
Retail Buyer | v1.2.5  | IGM flows available on integration excel but report showing only Flow 1A

### ISSUE THREAD

**Issue by pooja-1102** [ONDC-Official/pramaan#770]
NP has executed the reports and also available on integration excel but the executed flow for IGM is missing on report

bap id: preprod.lsp.ecom.ind.in
log11
https://docs.google.com/spreadsheets/d/1EMfxmI-N8tqrcQqxkXpdTR1Nj2jkYSri/edit?gid=1699296156#gid=1699296156

**Comment by ayush-yadav1999** [comment]
Hi @pooja-1102, this has been updated can you ask the NP to generate the report for the flows again 
<img width="1410" height="402" alt="Image" src="https://github.com/user-attachments/assets/bbdd9f6d-e7c0-4218-8be3-5e93afdd78be" />

**Comment by pallaviwemotive** [comment]
Checked for test id 1751519826135 still present

**Comment by ayush-yadav1999** [comment]
@pallaviwemotive , 1751519826135 this is an old test id can you please ask the NP to generate the report again

**Comment by pooja-1102** [comment]
@ayush-yadav1999 still facing this issue with current execution.
 Test Report ID: 1751880807268 
https://docs.google.com/spreadsheets/d/1ra9Amc0lFYEMRS2nZTTq5_I0f0J41wS8/edit?gid=862844286#gid=862844286

**Comment by pooja-1102** [comment]
<img width="1792" height="919" alt="Image" src="https://github.com/user-attachments/assets/61869353-2c80-4511-ab8f-7a6fc0b07c5a" />

**Comment by Shreshthsharma0109** [comment]
Hi @pooja-1102 ,
This was fixed. Attaching recently generated report's screenshot.

<img width="1326" height="537" alt="Image" src="https://github.com/user-attachments/assets/2c76076a-8584-463a-8d02-16bb871fcc15" />

**Comment by pooja-1102** [comment]
@shanusingh13 still facing issue
https://docs.google.com/spreadsheets/d/1oGDAR-Vg6pX85NYZ6DAlfefWkUrxUfi1/edit?gid=584407258#gid=584407258

**Comment by Nirdosh3312** [comment]
Hi @pooja-1102 / @Shreshthsharma0109 The test cases have been skipped due to exception during report generation thus they are not visible in the report. Here, the reports need to be generated again properly.

**Comment by pooja-1102** [comment]
This will be verified again with the new logistics buyer with v1.2.5 implement.

**Comment by pooja-1102** [comment]
this is not fixed, still not showing IGM reports

**Comment by pooja-1102** [comment]
updated details:
bap id: ondc.dev.bms.qwipo.com
LOG10
Logistics Buyer
Staging

**Comment by pooja-1102** [comment]
NPs still facing this issue

**Comment by ayush-yadav1999** [comment]
Hi @pooja-1102 is the same NP facing this issue ?

**Comment by pooja-1102** [comment]
yes

**Comment by ayush-yadav1999** [comment]
Hi @pooja-1102 let's schedule a call for this today

**Comment by pooja-1102** [comment]
scheduled for 12 PM

**Comment by ayush-yadav1999** [comment]
This issue has been resolved
