### ISSUE TITLE
Logistics Seller | V1.2.0 | Invalid/optional failures on report| flow 4

### ISSUE THREAD

**Issue by pooja-1102** [ONDC-Official/pramaan#781]
<img width="1792" alt="Image" src="https://github.com/user-attachments/assets/074dbd27-53b9-4221-80ca-b1955c26d994" />

details:

[1751612802725_seller_logs.json](https://github.com/user-attachments/files/21057095/1751612802725_seller_logs.json)

**Comment by shanusingh13** [comment]
Hi @pooja-1102, i am working on it, will update once it is fixed and deployed

**Comment by shanusingh13** [comment]
@pooja-1102 , this is has been fixed and deployed. please recheck and confirm

**Comment by pooja-1102** [comment]
@shanusingh13 still facing this issue
Test Report ID: 1751964612759

**Comment by shanusingh13** [comment]
Hi @pooja-1102 this issue has been fixed, please check again and do let me know if it still exists

**Comment by pooja-1102** [comment]
@shanusingh13 partially fixed:

<img width="1792" height="909" alt="Image" src="https://github.com/user-attachments/assets/8529c0cb-5a8b-4196-b103-dcfdd2f51c2b" />

**Comment by shanusingh13** [comment]
Hi @pooja-1102, this issue has been fixed, please check again and do let me know if it still exists

**Comment by shanusingh13** [comment]
Hi @pooja-1102, this issue has been fixed, please check again and do let me know if it still exists
