### ISSUE TITLE
BPP Testing : Return flows: In update call of RET 11 only parent item id and base item id should be used to return product but we are sending return request for customization also

### ISSUE THREAD

**Issue by pallaviwemotive** [ONDC-Official/pramaan#886]
BPP id:- staging.smaan.in
Transaction id:- cc3de9e3-f0a9-4d37-bed9-35a619e8031f
Domain: - RET 11

Description:-

When buyer app sends return request then in update call we need to mention only parent item id and its base item id

**Comment by Ashu-14-oct** [comment]
Hi @pooja-1102 , could you confirm if we send custom items in the return request or not?

**Comment by pooja-1102** [comment]
@Ashu-14-oct @Nirdosh3312 can we pick this item on priority

**Comment by Ashu-14-oct** [comment]
Hi @pooja-1102, this is fixed.

**Comment by pallaviwemotive** [comment]
TRansaction id- bcf3d873-f142-4b61-8d0e-c954a767934d
bpp id- integrations-preprod.channelier.com 
@Ashu-14-oct  please check this details issue still presents

**Comment by Ashu-14-oct** [comment]
{
                    "code": "return_request",
                    "list": [
 
                      {
                        "code": "item_id",
                        "value": "CU1000I0"
                      },   
                      {
                        "code": "parent_item_id",
                        "value": "item_1756469746368"
                      } 
                    ]
} 
please confirm should it be only like this? @pallaviwemotive

**Comment by Ashu-14-oct** [comment]
@pallaviwemotive can you please check now and confirm
