### ISSUE TITLE
TRV 11 - V2.01.Intracity Busses Issues

### ISSUE THREAD

**Issue by Ganesh11772** [ONDC-Official/pramaan#914]
Journey pass flow:-
on_search:-Verify the presence of 'message.catalog.providers[0].fulfillments[0].tags' and that should be an array- fulfillments tags missing
select:- fulfillments.id is missing
on_select:-message.order.items.time.duration incorrectly sent as PT5M for Journey pass

"transaction_id": "2afca197-b575-40ac-87fe-87a76182027c" for reference- Pass

Below are some false positive & optional test cases
1.Verify the presence of 'message.order.items[0].descriptor.images' which is an array- Mark this test case as optional
2.should verify the version of the payload- Flase positive test case
3.Verify the presence of 'message.order.quote.breakup[1].item' which is an object- false positive test case

Some test cases are failed & some are false positive please find report ids below
Pramaan Test Report ID: 1753957819765 generated at: "2025-07-31T10:34:25.431Z"- Mock Seller- Pass flow
Pramaan Test Report ID: 1753957822891 generated at: "2025-07-31T10:34:18.822Z"- Mock buyer- Pass flow
Pramaan Test Report ID: 1753953645802 generated at: "2025-07-31T10:17:34.404Z"- Mock buyer -Purchase journey flow
Pramaan Test Report ID: 1753953642936 generated at: "2025-07-31T10:17:25.437Z"- Mock buyer - Purchase journey flow

"transaction_id": "1c35fb61-7acc-40fb-a4c9-5add3961a4ea",- Purchase Journey flow

**Comment by DisasterDeveloper** [comment]
@Ganesh11772 , this has been fixed , please check

**Comment by Ganesh11772** [comment]
Test case related issues not fixed. Mock seller 83 test cases failed & some of them are false positive. Please look into this.
