### ISSUE TITLE
Retail Buyer & seller | integartion report showing 10 A and 10 B for RSF flows but pramaan GUI says 11 A and 11B

### ISSUE THREAD

**Issue by pooja-1102** [ONDC-Official/pramaan#976]
<img width="1792" height="853" alt="Image" src="https://github.com/user-attachments/assets/0ae53872-30b8-419c-87ca-bb8d0b955bc4" />

**Comment by ayush-yadav1999** [comment]
@shanusingh13 pls update on this

**Comment by shanusingh13** [comment]
Hi @pooja-1102, this issue has been fixed, please recheck

**Comment by pallaviwemotive** [comment]
Hi @shanusingh13  this issue still exists

**Comment by shanusingh13** [comment]
hi @pooja-1102, This issue has been fixed. I’ve attached the screenshot for your reference

<img width="1242" height="398" alt="Image" src="https://github.com/user-attachments/assets/4252902f-b991-466e-ab81-47d77bb907fc" />

**Comment by pallaviwemotive** [comment]
@shanusingh13  please check attachment it still showing 10 for Buyer

<img width="1190" height="257" alt="Image" src="https://github.com/user-attachments/assets/0d40ac48-0be2-45c4-8885-171ef6518496" />

**Comment by ayush-yadav1999** [comment]
Hi @pallaviwemotive, this would affect the new flows which get saved, as an exception I have updated this for this particular NP. Please check this.

**Comment by pallaviwemotive** [comment]
ok
